// Generated by CoffeeScript 1.6.2
(function() {
  define(function(require) {
    var Backbone;

    Backbone = require('backbone');
    return {
      initialize: function() {
        return $(document).on('click', 'a:not([data-bypass])', function(e) {
          var href;

          href = $(this).attr('href');
          if (href != null) {
            e.preventDefault();
            return Backbone.history.navigate(href, {
              'trigger': true
            });
          }
        });
      }
    };
  });

}).call(this);
