// Generated by CoffeeScript 1.6.2
(function() {
  require.config({
    paths: {
      'jquery': '../lib/jquery/jquery',
      'underscore': '../lib/underscore-amd/underscore',
      'backbone': '../lib/backbone-amd/backbone',
      'domready': '../lib/requirejs-domready/domReady',
      'text': '../lib/requirejs-text/text',
      'html': '../html'
    },
    shim: {
      'underscore': {
        exports: '_'
      },
      'backbone': {
        deps: ['underscore', 'jquery'],
        exports: 'Backbone'
      }
    }
  });

}).call(this);
